Add buffer sizes for title screens.
gmarty/scumm-nes pull request #24
Opened 2024-09-03 16:08 UTC by robertmegone

I think I've done this correctly, adding buffer sizes for both title screens. They are identical across all different versions.

Thank you for your work on this project, it is fascinating. Currently ScummVM does not yet support displaying the title screens, so this code should hopefully serve as a starting point for that.

2024-09-04 10:00 UTC, gmarty requested changes
Thank you for the PR. Really appreciate the work.
I'm mostly happy with it, except the part about setting the buffer size in the title screens. I explained in a comment why I think it's better to not rely on it.
If you revert these changes, I'm happy to land everything else.

BTW, I looked at your profile and I played many of the games you worked on! It's a honour to have you contributed to this project.

2024-09-04 10:00 UTC, gmarty commented on src/lib/parser/parseRom.js
> +    const buffer = arrayBuffer.slice(offset, offset + length);
I'd rather keep it the way it was.
The reason why the length of titles is not set is because it can't be determined statically ahead of time. It's more robust to not provide the buffer length here. In the future, I want to be able to parse rom hacks too, so I'd rather not depend on set values when not needed.

2024-09-04 10:00 UTC, gmarty commented on src/lib/parser/parseTitles.js
> +  metadata.decompressedSize = gfx.length + nametableTmp.length + attributes.length;
If we don't set the size of the buffer (see comment above), the payload size must be calculated manually, e.g.:
```js
metadata.size = parser.pointer;
```

2024-09-04 10:00 UTC, gmarty commented on src/lib/resources.js
> +   sounds: [
I should really take the time to fill in these arrays with the proper values, but your change makes it work in the meantime. Thanks for that!

2024-09-04 10:00 UTC, gmarty commented on src/lib/resources.js
> +  titles: [[0x2701, 0x0B4C], [0x324d, 0x09CF]],
Probably better to revert these values here and below.

2024-09-06 14:37 UTC, robertmegone commented
I'll close this, I hadn't thought about rom hacks and the only other change was already covered in my other pull request.

Thanks for the feedback!

2024-09-06 14:37 UTC, closed without merging